// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnVsOl0-N5TLn1mRa-jvEzO9NfFprNP2A',
    appId: '1:1026578504585:web:774cd111aeba017a74df58',
    messagingSenderId: '1026578504585',
    projectId: 'elbahaoui-flutterproject',
    authDomain: 'elbahaoui-flutterproject.firebaseapp.com',
    storageBucket: 'elbahaoui-flutterproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkFmFp1In8ARllWXZfonAXp6tIMCGT-hY',
    appId: '1:1026578504585:android:8de0a47c42d09dc974df58',
    messagingSenderId: '1026578504585',
    projectId: 'elbahaoui-flutterproject',
    storageBucket: 'elbahaoui-flutterproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAy-5rdbwWXFafPonXtnN_gcV5uwkSROo',
    appId: '1:1026578504585:ios:362e9a2e55eb8f6574df58',
    messagingSenderId: '1026578504585',
    projectId: 'elbahaoui-flutterproject',
    storageBucket: 'elbahaoui-flutterproject.firebasestorage.app',
    iosBundleId: 'com.example.elbahaApp',
  );
}
